In [1]:
import pandas as pd
df = pd.read_csv('sorted_128_100.csv')

In [9]:
len(df['4']) / 30

1188.9666666666667

In [6]:
len(df['4'].unique())

752

In [21]:
df['4'].iloc[0]

'Unnamed Road, Changping Qu, Beijing Shi, 중국'

In [25]:
df['4'].unique()

array(['Unnamed Road, Changping Qu, Beijing Shi, 중국', '0',
       '101 Hui Long Guan Xi Da Jie, Changping Qu, Beijing Shi, 중국 100192',
       '징진깡기안, 하이디안큐, 비징시, 중국',
       'Yan Ling Chuan Xiang Jia Chang Cai, Haidian Qu, Beijing Shi, 중국',
       '징구슈 후아 런후아 유 꽁시, 하이디안 큐, 비징시, 중국',
       'Shang Di San Jie, Haidian Qu, Beijing Shi, 중국',
       'Li Fa(Bei Jing Shi Hai Dian Qua Lv Hua Dui Xi Bei), Haidian Qu, Beijing Shi, 중국',
       'Bei Jing Da Xue Tu Shu Guan, Haidian Qu, Beijing Shi, 중국',
       '62 Bei Si Huan Xi Lu, Zhong Guan Cun, Haidian Qu, Beijing Shi, 중국 100810',
       'Ou Mei Hui Gou Wu Zhong Xin, Zhong Guan Cun, Haidian Qu, Beijing Shi, 중국',
       'B 12-1 Ke Xue Yuan Nan Lu, Haidian Qu, Beijing Shi, 중국 100081',
       '징구앙띠앙 삐이징위이 Xing Zhi Zao Chang (동규), 하디안 쿼, 비이징샤이, 중국',
       'Zhong Guan Cun Dong Lu, Shuang Yu Shu, Haidian Qu, Beijing Shi, 중국',
       'Tong Cheng Jie, Changping Qu, Beijing Shi, 중국',
       '85 Hui Long Guan Xi Da Jie, Changping Qu, Beijing Shi, 중국 10

In [2]:
import urllib.request, json
import pandas as pd
import os
import sys
import json

client_id = "65xw2v8rw33_NOSdyN3z"
client_secret = "PJrpJbOVjA"
a = []

for i in range(len(df)):
    if df['4'].iloc[i] != 0:
        encText = urllib.parse.quote(df['4'].iloc[i])
        data = "source=zh-CN&target=ko&text=" + encText
        url = "https://openapi.naver.com/v1/papago/n2mt"
        request = urllib.request.Request(url)
        request.add_header("X-Naver-Client-Id",client_id)
        request.add_header("X-Naver-Client-Secret",client_secret)
        response = urllib.request.urlopen(request, data=data.encode("utf-8"))
        rescode = response.getcode()
        if(rescode==200):
            response_body = response.read()
            result_str = response_body.decode('utf-8') # type가 string이네

            result = json.loads(result_str) 
            address = result['message']['result']['translatedText']
            a.append(address)
        else:
            print("Error Code:" + rescode)
    else:
        a.append(0)

HTTPError: HTTP Error 429: Too Many Requests

In [3]:
a

['Unnamed Road, Changping Qu, Beijing Shi, 중국',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '101 Hui Long Guan Xi Da Jie, Changping Qu, Beijing Shi, 중국 100192',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '징진깡기안, 하이디안큐, 비징시, 중국',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'Yan Ling Chuan Xiang Jia Chang Cai, Haidian Qu, Beijing Shi, 중국',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '징구슈 후아 런후아 유 꽁시, 하이디안 큐, 비징시, 중국',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 

In [28]:
df.to_csv('sorted_128_100_hangeul.csv')

# 한글 전처리

In [9]:
import pandas as pd
df = pd.read_csv('sorted_128_100_hangeul.csv')

In [10]:
df['4'].unique()

array(['Unnamed Road, Changping Qu, Beijing Shi, 중국', '0',
       '101 Hui Long Guan Xi Da Jie, Changping Qu, Beijing Shi, 중국 100192',
       '진깡기안, 하이디안, 비징시, 중국',
       'Yan Ling Chuan Xiang Jia Chang Cai, Haidian Qu, Beijing Shi, 중국',
       '징구후後亞유꽁市, heidyan큐, 非징市, 中國',
       'Shang Di San Jie, Haidian Qu, Beijing Shi, 중국',
       'Li Fa(Bei Jing Shi Hai Dian Qua Lv Hua Dui Xi Bei), Haidian Qu, Beijing Shi, 중국',
       'Bei Jing Da Xue Tu Shu Guan, Haidian Qu, Beijing Shi, 중국',
       '62 Bei Si Huan Xi Lu, Zhong Guan Cun, Haidian Qu, Beijing Shi, 중국 100810',
       'Ou Mei Hui Gou Wu Zhong Xin, Zhong Guan Cun, Haidian Qu, Beijing Shi, 중국',
       'B 12-1 Ke Xue Yuan Nan Lu, Haidian Qu, Beijing Shi, 중국 100081',
       '띠띠 X X X X XXing Zhi Zao Chang(동규), 하디안쿼, 비이샤이, 중국',
       'Zhong Guan Cun Dong Lu, Shuang Yu Shu, Haidian Qu, Beijing Shi, 중국',
       'Tong Cheng Jie, Changping Qu, Beijing Shi, 중국',
       '85 Hui Long Guan Xi Da Jie, Changping Qu, Beijing Shi, 중국 102208',
   

In [11]:
df['4'].unique()

array(['Unnamed Road, Changping Qu, Beijing Shi, 중국', '0',
       '101 Hui Long Guan Xi Da Jie, Changping Qu, Beijing Shi, 중국 100192',
       '진깡기안, 하이디안, 비징시, 중국',
       'Yan Ling Chuan Xiang Jia Chang Cai, Haidian Qu, Beijing Shi, 중국',
       '징구후後亞유꽁市, heidyan큐, 非징市, 中國',
       'Shang Di San Jie, Haidian Qu, Beijing Shi, 중국',
       'Li Fa(Bei Jing Shi Hai Dian Qua Lv Hua Dui Xi Bei), Haidian Qu, Beijing Shi, 중국',
       'Bei Jing Da Xue Tu Shu Guan, Haidian Qu, Beijing Shi, 중국',
       '62 Bei Si Huan Xi Lu, Zhong Guan Cun, Haidian Qu, Beijing Shi, 중국 100810',
       'Ou Mei Hui Gou Wu Zhong Xin, Zhong Guan Cun, Haidian Qu, Beijing Shi, 중국',
       'B 12-1 Ke Xue Yuan Nan Lu, Haidian Qu, Beijing Shi, 중국 100081',
       '띠띠 X X X X XXing Zhi Zao Chang(동규), 하디안쿼, 비이샤이, 중국',
       'Zhong Guan Cun Dong Lu, Shuang Yu Shu, Haidian Qu, Beijing Shi, 중국',
       'Tong Cheng Jie, Changping Qu, Beijing Shi, 중국',
       '85 Hui Long Guan Xi Da Jie, Changping Qu, Beijing Shi, 중국 102208',
   

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = df['4'].unique()
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'unnamed': 653, 'road': 591, 'changping': 280, 'qu': 579, 'beijing': 255, 'shi': 611, '중국': 831, '101': 82, 'hui': 388, 'long': 475, 'guan': 352, 'xi': 683, 'da': 299, 'jie': 417, '100192': 69, '진깡기안': 832, '하이디안': 835, '비징시': 827, 'yan': 716, 'ling': 469, 'chuan': 290, 'xiang': 687, 'jia': 409, 'chang': 275, 'cai': 266, 'haidian': 361, '징구후後亞유꽁市': 833, 'heidyan큐': 371, '非징市': 816, '中國': 770, 'shang': 603, 'di': 305, 'san': 598, 'li': 461, 'fa': 322, 'bei': 254, 'jing': 420, 'hai': 360, 'dian': 306, 'qua': 580, 'lv': 485, 'hua': 382, 'dui': 316, 'xue': 709, 'tu': 649, 'shu': 616, '62': 216, 'si': 625, 'huan': 385, 'lu': 479, 'zhong': 752, 'cun': 298, '100810': 77, 'ou': 548, 'mei': 510, 'gou': 348, 'wu': 680, 'xin': 693, '12': 104, 'ke': 451, 'yuan': 733, 'nan': 535, '100081': 47, '띠띠': 824, 'xxing': 714, 'zhi': 751, 'zao': 740, '동규': 823, '하디안쿼': 834, '비이샤이': 826, '

In [14]:
dict_ = vector.vocabulary_

In [18]:
dict_.keys()

dict_keys(['unnamed', 'road', 'changping', 'qu', 'beijing', 'shi', '중국', '101', 'hui', 'long', 'guan', 'xi', 'da', 'jie', '100192', '진깡기안', '하이디안', '비징시', 'yan', 'ling', 'chuan', 'xiang', 'jia', 'chang', 'cai', 'haidian', '징구후後亞유꽁市', 'heidyan큐', '非징市', '中國', 'shang', 'di', 'san', 'li', 'fa', 'bei', 'jing', 'hai', 'dian', 'qua', 'lv', 'hua', 'dui', 'xue', 'tu', 'shu', '62', 'si', 'huan', 'lu', 'zhong', 'cun', '100810', 'ou', 'mei', 'gou', 'wu', 'xin', '12', 'ke', 'yuan', 'nan', '100081', '띠띠', 'xxing', 'zhi', 'zao', '동규', '하디안쿼', '비이샤이', 'dong', 'shuang', 'yu', 'tong', 'cheng', '85', '102208', 'niu', 'zhuang', 'huang', 'he', '102200', '017', 'xian', 'dao', '30', '15', 'fu', '102249', 'shuiku', 'rd', '十三陵水库水库南路', 'chao', 'feng', 'an', 'kang', 'shan', 'qian', 'tian', 'hang', 'heng', 'xing', 'sha', 'er', 'rou', 'huo', 'shao', 'xia', 'qing', 'ti', 'bu', 'hao', 'lou', 'cui', 'gong', 'fan', 'xie', 'zi', 'bao', '龙腾苑五区2号楼7号底商', '110', '115', '100096', '50', 'ru', 'kou', 'guang', 'ning', 'shijin

In [ ]:
https://wikidocs.net/31698

In [38]:
vector.fit_transform(corpus).toarray().shape

(753, 837)

In [41]:
print(vector.fit_transform(corpus).toarray()[0])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [42]:
import torch
#torch.nn.MSELoss().

OSError: [WinError 1455] 이 작업을 완료하기 위한 페이징 파일이 너무 작습니다. Error loading "C:\Users\SungJin\anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.