In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 041.zip to 041.zip
User uploaded file "041.zip" with length 13863890 bytes


In [ ]:
!unzip 041.zip

In [ ]:
list_

In [1]:
import os
import pandas as pd
list_ = os.listdir('sorted_data/128/Trajectory/')

In [3]:
sorted_41 = []
for i in range(len(list_)):
    file_ = open('sorted_data/128/Trajectory/' + list_[i], 'r') 
    file = file_.readlines()
    file = file[6:]
    for j in range(len(file)):
        tmp = file[j].split(',')
        sorted_41.append([tmp[0], tmp[1], tmp[-2] + ' ' +tmp[-1][:-1]])

df = pd.DataFrame(sorted_41)
df[2] = pd.to_datetime(df[2])
df.sort_values(by = [2],inplace=True)
df = df.reset_index()
df = df[[0,1,2]]

NameError: name 'pd' is not defined

In [43]:
df[[0, 1]]

0            1                   2
0        39.9063099  116.2682616 2009-02-13 03:48:06
1        39.9062233  116.2682983 2009-02-13 03:48:07
2         39.906135  116.2683283 2009-02-13 03:48:09
3        39.9060466  116.2683749 2009-02-13 03:48:24
4        39.9061299  116.2683266 2009-02-13 03:48:29
...             ...          ...                 ...
1057038  39.8475133  116.6340183 2009-07-12 08:35:45
1057039  39.8476383  116.6337466 2009-07-12 08:35:46
1057040  39.8477566   116.633475 2009-07-12 08:35:47
1057041  39.8478899  116.6332016 2009-07-12 08:35:48
1057042  39.8480183  116.6329266 2009-07-12 08:35:49

[1057043 rows x 3 columns]

In [44]:
import torch
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

# Random seed to make results deterministic and reproducible
torch.manual_seed(0)


# def minmax_scaler(data):
#     numerator = data - np.min(data, 0)
#     denominator = np.max(data, 0) - np.min(data, 0)
#     return numerator / (denominator + 1e-7)


def build_dataset(time_series, seq_length):
    dataX = []
    dataY = []
    for i in range(0, len(time_series) - seq_length):
        _x = time_series[i:i + seq_length, :]
        _y = time_series[i + seq_length, [-1]]  # Next close price
        print(_x, "->", _y)
        dataX.append(_x)
        dataY.append(_y)
    print(dataX)
    print(dataY)
    return np.array(dataX), np.array(dataY)


seq_length = 7
data_dim = 5
hidden_dim = 15
output_dim = 1
learning_rate = 0.01 # 
iterations = 500

#xy = np.loadtxt("data-02-stock_daily.csv", delimiter=",")
xy = np.array(df[[0, 1]])
xy = xy[::-1]  # reverse order

train_size = int(len(xy) * 0.7)
train_set = xy[0:train_size]
test_set = xy[train_size - seq_length:]

# train_set = minmax_scaler(train_set)
# test_set = minmax_scaler(test_set)

trainX, trainY = build_dataset(train_set, seq_length)
testX, testY = build_dataset(test_set, seq_length)

trainX_tensor = torch.FloatTensor(trainX)
trainY_tensor = torch.FloatTensor(trainY)

testX_tensor = torch.FloatTensor(testX)
testY_tensor = torch.FloatTensor(testY)


class Net(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, layers):
        super(Net, self).__init__()
        self.rnn = torch.nn.LSTM(input_dim, hidden_dim, num_layers=layers, batch_first=True)
        self.fc = torch.nn.Linear(hidden_dim, output_dim, bias=True)

    def forward(self, x):
        x, _status = self.rnn(x)
        x = self.fc(x[:, -1])
        return x


net = Net(data_dim, hidden_dim, output_dim, 1)

# loss & optimizer setting
criterion = torch.nn.MSELoss() # mse, mae
optimizer = optim.Adam(net.parameters(), lr=learning_rate)

for i in range(iterations):

    optimizer.zero_grad()
    outputs = net(trainX_tensor)
    loss = criterion(outputs, trainY_tensor)
    loss.backward()
    optimizer.step()
    print(i, loss.item())

plt.plot(testY)
plt.plot(net(testX_tensor).data.numpy())
plt.legend(['original', 'prediction'])
plt.show()

Streaming output truncated to the last 5000 lines.
 ['39.8208299' '116.2074966']
 ['39.8210099' '116.2074983']] -> ['116.2075']
[['39.82009' '116.2074116']
 ['39.8202683' '116.2074449']
 ['39.8204516' '116.2074683']
 ['39.8206416' '116.2074866']
 ['39.8208299' '116.2074966']
 ['39.8210099' '116.2074983']
 ['39.8211933' '116.2075']] -> ['116.2074983']
[['39.8202683' '116.2074449']
 ['39.8204516' '116.2074683']
 ['39.8206416' '116.2074866']
 ['39.8208299' '116.2074966']
 ['39.8210099' '116.2074983']
 ['39.8211933' '116.2075']
 ['39.8213766' '116.2074983']] -> ['116.2074916']
[['39.8204516' '116.2074683']
 ['39.8206416' '116.2074866']
 ['39.8208299' '116.2074966']
 ['39.8210099' '116.2074983']
 ['39.8211933' '116.2075']
 ['39.8213766' '116.2074983']
 ['39.8215599' '116.2074916']] -> ['116.2074733']
[['39.8206416' '116.2074866']
 ['39.8208299' '116.2074966']
 ['39.8210099' '116.2074983']
 ['39.8211933' '116.2075']
 ['39.8213766' '116.2074983']
 ['39.8215599' '116.2074916']
 ['39.8217283' '

KeyboardInterrupt: ignored

In [110]:
import random
import numpy as np
import torch

# multivariate data preparation
from numpy import array
from numpy import hstack
 
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-2], sequences[end_ix-1, -2:]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)
 
# define input sequence
in_seq1 = array([x for x in range(0,100,10)])
in_seq2 = array([x for x in range(5,105,10)])
out_seq_1 = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
out_seq_2 = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
out_seq = hstack((out_seq_1, out_seq_2))
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((10, 2))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

In [111]:
dataset

array([[  0,   5,   5,  25],
       [ 10,  15,  45,  65],
       [ 20,  25,  85, 105],
       [ 30,  35, 125, 145],
       [ 40,  45, 165, 185],
       [ 50,  55,   5,  25],
       [ 60,  65,  45,  65],
       [ 70,  75,  85, 105],
       [ 80,  85, 125, 145],
       [ 90,  95, 165, 185]])

In [112]:
class MV_LSTM(torch.nn.Module):
    def __init__(self,n_features,seq_length):
        super(MV_LSTM, self).__init__()
        self.n_features = n_features
        self.seq_len = seq_length
        self.n_hidden = 20 # number of hidden states
        self.n_layers = 1 # number of LSTM layers (stacked)
    
        self.l_lstm = torch.nn.LSTM(input_size = n_features, 
                                 hidden_size = self.n_hidden,
                                 num_layers = self.n_layers, 
                                 batch_first = True)
        # according to pytorch docs LSTM output is 
        # (batch_size,seq_len, num_directions * hidden_size)
        # when considering batch_first = True
        self.l_linear = torch.nn.Linear(self.n_hidden*self.seq_len, 1)
        
    
    def init_hidden(self, batch_size):
        # even with batch_first = True this remains same as docs
        hidden_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        cell_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        self.hidden = (hidden_state, cell_state)
    
    
    def forward(self, x, y):        
        batch_size, seq_len, _ = x.size()
        print(batch_size, seq_len)
        lstm_out_x, self.hidden = self.l_lstm(x,self.hidden)
        lstm_out_y, self.hidden = self.l_lstm(y,self.hidden)
        # lstm_out(with batch_first = True) is 
        # (batch_size,seq_len,num_directions * hidden_size)
        # for following linear layer we want to keep batch_size dimension and merge rest       
        # .contiguous() -> solves tensor compatibility error
        x = lstm_out_x.contiguous().view(batch_size,-1)
        y = lstm_out_y.contiguous().view(batch_size,-1)
        return self.l_linear(x), self.l_linear(y)

In [113]:
n_features = 2 # this is number of parallel inputs
n_timesteps = 3 # this is number of timesteps

# convert dataset into input/output
X, y = split_sequences(dataset, n_timesteps)
print(X.shape, y.shape)

# create NN
mv_net = MV_LSTM(n_features,n_timesteps)
criterion_x = torch.nn.MSELoss() # reduction='sum' created huge loss value
criterion_y = torch.nn.MSELoss() # reduction='sum' created huge loss value

optimizer = torch.optim.Adam(mv_net.parameters(), lr=1e-1)

train_episodes = 500
batch_size = 16

(8, 3, 2) (8, 2)


In [108]:
mv_net.train()
for t in range(train_episodes):
    for b in range(0,len(X),batch_size):
        inpt = X[b:b+batch_size,:,:]
        target = y[b:b+batch_size]    
        x_batch = torch.tensor(inpt,dtype=torch.float32)    
        y_batch = torch.tensor(target,dtype=torch.float32)
        print(x_batch)
        print(y_batch)
        mv_net.init_hidden(x_batch.size(0))
    #    lstm_out, _ = mv_net.l_lstm(x_batch,nnet.hidden)    
    #    lstm_out.contiguous().view(x_batch.size(0),-1)
        output = mv_net(x_batch[:,:,0], y_batch[:,:,1])
        print(output)
        loss = criterion_x(output.view(-1), y_batch[:, 0]) + criterion_y(output.view(-1), y_batch[:, 1])
        loss.backward()
        optimizer.step()        
        optimizer.zero_grad() 
    print('step : ' , t , 'loss : ' , loss.item())

tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
tensor([[ 85., 105.],
        [125., 145.],
        [165., 185.],
        [  5.,  25.],
        [ 45.,  65.],
        [ 85., 105.],
        [125., 145.],
        [165., 185.]])


IndexError: too many indices for tensor of dimension 2

In [20]:
df = pd.DataFrame(sorted_41)

In [6]:
import os
list_ = os.listdir('Trajectory/')

In [83]:
import urllib.request, json
import pandas as pd
import os
import sys
import json

# 데이터를 
sorted_128 = []

# client_id = "65xw2v8rw33_NOSdyN3z"
# client_secret = "PJrpJbOVjA"
    
for i in range(len(list_)):
    file_ = open('sorted_data/128/Trajectory/' + list_[i], 'r') 
    file = file_.readlines()
    file = file[6:]
    for j in range(len(file)):
        tmp = file[j].split(',')
        if j % 20 == 0:
            print(j)
            with urllib.request.urlopen("https://maps.googleapis.com/maps/api/geocode/json?latlng=" + tmp[0] + "," + tmp[1] + "&key=AIzaSyClbiBnOUKA_p-VzyF7R7cwdnQ1yHrTtHw&language=ko") as url:
                data = json.loads(url.read().decode())
            print(data)
#             address = ''
#             for k in range(10):
#                 try:
#                     if len(tmp) < len(data['results'][i]['formatted_address']):
#                         address = data['results'][i]['formatted_address']
# #                         address = data['results'][i]['formatted_address']
# #                         encText = urllib.parse.quote(address)
# #                         data = "source=zh-CN&target=ko&text=" + encText
# #                         url = "https://openapi.naver.com/v1/papago/n2mt"
# #                         request = urllib.request.Request(url)
# #                         request.add_header("X-Naver-Client-Id",client_id)
# #                         request.add_header("X-Naver-Client-Secret",client_secret)
# #                         response = urllib.request.urlopen(request, data=data.encode("utf-8"))
# #                         rescode = response.getcode()
# #                         if(rescode==200):
# #                             response_body = response.read()
# #                             result_str = response_body.decode('utf-8') # type가 string이네

# #                             result = json.loads(result_str) 
# #                             address = result['message']['result']['translatedText']
# #                             break
#     #                     else:
#     #                         print("Error Code:" + rescode)
#                 except IndexError:
#                     pass
#             sorted_128.append([tmp[0], tmp[1], tmp[-2], tmp[-1][:-1], address])
#         else:
#             sorted_128.append([tmp[0], tmp[1], tmp[-2], tmp[-1][:-1], 0])
# df = pd.DataFrame(sorted_128)
# df.to_csv('sorted_128.csv')

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
0
20
0
20
40
60
80
100
0
20
40
60
0
20
40
0
20
40
60
0
20
40
60
0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
0
20
0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
0
20
40
0
20
0
20
40
0
20
0
20
4

5700
5720
5740
5760
5780
5800
5820
5840
5860
5880
5900
5920
5940
5960
5980
6000
6020
6040
6060
6080
6100
6120
6140
6160
6180
6200
6220
6240
6260
6280
6300
6320
6340
6360
6380
6400
6420
6440
6460
6480
6500
6520
6540
6560
6580
6600
6620
6640
6660
6680
6700
6720
6740
6760
6780
6800
6820
6840
6860
6880
6900
6920
6940
6960
6980
7000
7020
7040
7060
7080
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840
1860
1880
1900
1920
1940
1960
1980
2000
2020
2040
2060
2080
2100
2120
2140
2160
2180
2200
2220
2240
2260


1680
1700
1720
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
0
20
40
60
80
100
120
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40


0
20
40
60
80
100
120
140
160
180
200
220
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
0
20
40
60
80
100
120
140
160
180
200
220
0
20
40
60
80
100
120
140
160
180
200
220
240
260
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
0
20
40
60
80
100
0
20
40
60
80
100
120
140
160
180
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
0
20
40
60
80
100
120
140
160
180
200
220
240
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380


2080
2100
2120
2140
2160
2180
2200
2220
2240
2260
2280
2300
2320
2340
2360
2380
2400
2420
2440
2460
2480
2500
2520
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840
1860
1880
1900
1920
1940
1960
1980
2000
2020
2040
2060
2080
2100
2120
2140
2160
2180
2200
2220
2240
2260
2280
2300
2320
2340
2360
2380
2400
2420
2440
2460
2480
2500
2520
2540
2560
2580
2600
2620
2640
2660
2680
2700
2720
2740
2760
2780
2800
2820
2840
2860
2880
2900
2920
2940
2960
29

2740
2760
2780
2800
2820
2840
2860
2880
2900
2920
2940
2960
2980
3000
3020
3040
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
0
20
40
60
80
100
120
140
160
180
200
220
240
260
0
20
40
60
80
100
120
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
0
20
40
60
80
100
0

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840
1860
1880
1900
1920
1940
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
0
20
40
60
80
100
120
140
160
180
200
220
240
260
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280


180
200
220
240
260
0
20
40
60
0
20
40
60
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840
1860
1880
1900
1920
1940
1960
1980
2000
2020
2040
2060
0
0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
60
80
100
120
140
0
20
40
60
80
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
0
20
40
60
80
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
90

0
20
40
60
80
0
20
40
60
80
100
120
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840
1860
1880
1900
1920
1940
1960
1980
0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
220
240
260
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
0
20
40
60
80
100
120
140
160
180
200
2

180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
0
20
40
60
80
100
120
140
160
180
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
0
20
40
60
80
100
120
140
160
180
200
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
0
20
40
60
80
100
120
140
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
0
20
40
60
80
100
120
140
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
0
20
40
60
80
0
20
40
60
80


1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840
1860
1880
1900
1920
1940
1960
1980
2000

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
0
20
40
60
80
100
120
140
160
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
0
20
40
60
80
100
120
140
160
180
0
20
40
60
80
100
120
140
160
180
200
220
0
20
40
60
80
100
120
140
160
180
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
60
80
100
120
140
160
180
200
0
20
40
60
80
100
120
140
160
180
200
220


0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
0
20
40
60
80
100
120
140
160
180
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
160
180
200
220
240
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
9

2940
2960
2980
3000
3020
3040
3060
3080
3100
3120
3140
3160
3180
3200
3220
3240
3260
3280
3300
3320
3340
3360
3380
3400
3420
3440
3460
3480
3500
3520
3540
3560
3580
3600
3620
3640
3660
3680
3700
3720
3740
3760
3780
3800
3820
3840
3860
3880
3900
3920
3940
3960
3980
4000
4020
4040
4060
4080
4100
4120
4140
4160
4180
4200
4220
4240
4260
4280
4300
4320
4340
4360
4380
4400
4420
4440
4460
4480
4500
4520
4540
4560
4580
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840
1860
1880
1900
1920
1940
1960
1980
2000
2020
2040
2060
2080
2100
2120
2140
2160
2180
2200
2220
2240
2260
2280
2300
2320
2340
2360
2380
2400
2420
2440
2460
2480
2500
2520
2540
2

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
1460
1480
1500
1520
1540
1560
1580
1600
1620
1640
1660
1680
1700
1720
1740
1760
1780
1800
1820
1840
1860
1880
1900
1920
0
20
40
60
80
100


0
20
40
60
80
100
120
140
160
180
200
220
240
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
0
20
40
60
80
100
120
140
160
180
200
220
240
260
0
2

740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
1220
1240
1260
1280
1300
1320
1340
1360
1380
1400
1420
1440
0
20
40
60
80
100
120
140
160
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
0
20
40
60
80
100
120
140
160
180
200
220
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
0
20
40
60
80
0
20
40
60
80
100
120
140
160
180
200
220
240
260
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
0
20
40
60
80
100
120
140
160
180
200
220
240
0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
0
20
40
60
80
0
20
40
60


0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
0
20
40
60
80
100
120
140
160
180
200
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
0
20
40
60
80
100
120
140
160
180
200
220
0
20
40
60
80
100
120
140
160
180
0
20
40
60
80
100
120
140
160
180
200
220
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
0
20
40
60
80
100
120
140
160
180
200
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
0
20
40
60
80
100
120
140
160
180
200
220
240
0
20
40
60
80
100
120
140
160
180
200
0


0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
0
20
40
60
80
100
120
140
160
0
20
40
60
80
100
120
140
160
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
0
20
40
60
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
0
20
40
60
80
100
120
140
160
180
200
220
240
0
20
40
60
80
100
120
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
0
20
40
60
8

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
0
20
40
60
80
100
120
140
160
180
200
220
240
260
0
20
40
60
80
100
120
140
160
180
200
0
20
40
60
80
100
120
140
0
20
40
60
80
100
120
140
160
180
200
220
240
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
960
980
1000
1020
1040
1060
1080
1100
1120
1140
1160
1180
1200
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
0
20
40
60
80
100
120
140
160
180
200
220
240
260
0
20
40
60
80
100
120
140
160
180
200
220
240
0
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
760
780
800
820
840
860
880
900
920
940
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
0
20
40
60
80
100
120
140
160
180
200
22

20
40
60
80
100
120
140
160
0
20
40
60
80
100
120
140
160
180
0
20
40
60
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
0
20
40
60
80
100
120
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
0
20
40
60
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
0
20
40
60
80
100
120
140
160
180
200
2

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
700
720
740
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
0
20
40
60
80
100
120
140
160
180


In [63]:
import pandas as pd
df = pd.read_csv('sorted_128_last.csv')

C:\Users\SungJin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [81]:
df[-200:]

Unnamed: 0          0           1           2         3    4
1110623     1110623  39.951795  116.372782  2010-08-29  10:09:40  NaN
1110624     1110624  39.951693  116.372802  2010-08-29  10:09:44    0
1110625     1110625  39.951607  116.372813  2010-08-29  10:09:48    0
1110626     1110626  39.951527  116.372830  2010-08-29  10:09:52    0
1110627     1110627  39.951510  116.372838  2010-08-29  10:09:56    0
...             ...        ...         ...         ...       ...  ...
1110818     1110818  39.935735  116.410697  2010-08-29  10:29:29    0
1110819     1110819  39.935768  116.410728  2010-08-29  10:29:31    0
1110820     1110820  39.935822  116.410753  2010-08-29  10:29:33    0
1110821     1110821  39.935863  116.410745  2010-08-29  10:29:35    0
1110822     1110822  39.935893  116.410732  2010-08-29  10:29:37    0

[200 rows x 6 columns]

In [114]:
import random
import numpy as np
import torch

# multivariate data preparation
from numpy import array
from numpy import hstack
 
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)
 
# define input sequence
in_seq1 = array([x for x in range(0,100,10)])
in_seq2 = array([x for x in range(5,105,10)])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

In [171]:
class MV_LSTM(torch.nn.Module):
    def __init__(self,n_features,seq_length):
        super(MV_LSTM, self).__init__()
        self.n_features = n_features
        self.seq_len = seq_length
        self.n_hidden = 20 # number of hidden states
        self.n_layers = 1 # number of LSTM layers (stacked)
    
        self.l_lstm = torch.nn.LSTM(input_size = n_features, 
                                 hidden_size = self.n_hidden,
                                 num_layers = self.n_layers, 
                                 batch_first = True)
        # according to pytorch docs LSTM output is 
        # (batch_size,seq_len, num_directions * hidden_size)
        # when considering batch_first = True
        self.l_linear = torch.nn.Linear(self.n_hidden*self.seq_len, 1)
        
    
    def init_hidden(self, batch_size):
        # even with batch_first = True this remains same as docs
        hidden_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        cell_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        self.hidden = (hidden_state, cell_state)
    
    
    def forward(self, x):
        print(x)
        batch_size, seq_len, _ = x.size()
        
        lstm_out, self.hidden = self.l_lstm(x,self.hidden)
        # lstm_out(with batch_first = True) is 
        # (batch_size,seq_len,num_directions * hidden_size)
        # for following linear layer we want to keep batch_size dimension and merge rest       
        # .contiguous() -> solves tensor compatibility error
        x = lstm_out.contiguous().view(batch_size,-1)
        return self.l_linear(x)

In [172]:
n_features = 1 # this is number of parallel inputs
n_timesteps = 3 # this is number of timesteps

# convert dataset into input/output
X, y = split_sequences(dataset, n_timesteps)
y = np.vstack([y,y])
print(X.shape, y.shape)

# create NN
mv_net_x = MV_LSTM(n_features,n_timesteps)
mv_net_y = MV_LSTM(n_features, n_timesteps)
criterion = torch.nn.MSELoss() # reduction='sum' created huge loss value
optimizer = torch.optim.Adam(mv_net.parameters(), lr=1e-1)

train_episodes = 500
batch_size = 16

(8, 3, 2) (2, 8)


In [173]:
np.vstack([y,y])

array([[ 45,  65,  85, 105, 125, 145, 165, 185],
       [ 45,  65,  85, 105, 125, 145, 165, 185],
       [ 45,  65,  85, 105, 125, 145, 165, 185],
       [ 45,  65,  85, 105, 125, 145, 165, 185]])

In [128]:
X

array([[[ 0,  5],
        [10, 15],
        [20, 25]],

       [[10, 15],
        [20, 25],
        [30, 35]],

       [[20, 25],
        [30, 35],
        [40, 45]],

       [[30, 35],
        [40, 45],
        [50, 55]],

       [[40, 45],
        [50, 55],
        [60, 65]],

       [[50, 55],
        [60, 65],
        [70, 75]],

       [[60, 65],
        [70, 75],
        [80, 85]],

       [[70, 75],
        [80, 85],
        [90, 95]]])

In [170]:
mv_net_x.train()
mv_net_y.train()

for t in range(train_episodes):
    for b in range(0,len(X),batch_size):
        inpt = X[b:b+batch_size,:,:]
        target = y[b:b+batch_size]    
        
        x_batch = torch.tensor(inpt[:,:,0],dtype=torch.float32)
        y_batch = torch.tensor(inpt[:,:,1],dtype=torch.float32)
        target_batch = torch.tensor(target,dtype=torch.float32)
    
        mv_net_x.init_hidden(x_batch.size(0))
        mv_net_y.init_hidden(y_batch.size(0))
    #    lstm_out, _ = mv_net.l_lstm(x_batch,nnet.hidden)    
    #    lstm_out.contiguous().view(x_batch.size(0),-1)
        x_batch = x_batch.reshape(8,3,1) # 3 채널로 맞춰줘야 함
        y_batch = y_batch.reshape(8,3,1)
        output_x = mv_net_x(x_batch)
        output_y = mv_net_y(y_batch)
        loss = criterion(output_x.view(-1), target_batch[0,:]) + criterion(output_y.view(-1), target_batch[1,:])
        
        loss.backward()
        optimizer.step()        
        optimizer.zero_grad() 
    print('step : ' , t , 'loss : ' , loss.item())

tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  0 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
 

tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  24 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],


step :  52 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  53 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],


step :  83 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  84 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],


tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  104 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],

         [95.]]])
step :  131 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  132 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20

step :  157 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  158 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.]

tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  182 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],

step :  206 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  207 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.]

         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  234 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]]

step :  264 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  265 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.]

tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  300 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],

         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  330 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]]

         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  362 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]]

step :  389 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  390 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.]

tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  419 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],

tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  444 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],

tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],
         [40.],
         [50.]],

        [[40.],
         [50.],
         [60.]],

        [[50.],
         [60.],
         [70.]],

        [[60.],
         [70.],
         [80.]],

        [[70.],
         [80.],
         [90.]]])
tensor([[[ 5.],
         [15.],
         [25.]],

        [[15.],
         [25.],
         [35.]],

        [[25.],
         [35.],
         [45.]],

        [[35.],
         [45.],
         [55.]],

        [[45.],
         [55.],
         [65.]],

        [[55.],
         [65.],
         [75.]],

        [[65.],
         [75.],
         [85.]],

        [[75.],
         [85.],
         [95.]]])
step :  475 loss :  15332.43359375
tensor([[[ 0.],
         [10.],
         [20.]],

        [[10.],
         [20.],
         [30.]],

        [[20.],
         [30.],
         [40.]],

        [[30.],

In [165]:
target_batch[:,0]

tensor([45., 45.])

In [141]:
import random
import numpy as np
import torch

# multivariate data preparation
from numpy import array
from numpy import hstack
 
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)
 
# define input sequence
in_seq1 = array([x for x in range(0,100,10)])
in_seq2 = array([x for x in range(5,105,10)])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

In [149]:
class MV_LSTM(torch.nn.Module):
    def __init__(self,n_features,seq_length):
        super(MV_LSTM, self).__init__()
        self.n_features = n_features
        self.seq_len = seq_length
        self.n_hidden = 20 # number of hidden states
        self.n_layers = 1 # number of LSTM layers (stacked)
    
        self.l_lstm = torch.nn.LSTM(input_size = n_features, 
                                 hidden_size = self.n_hidden,
                                 num_layers = self.n_layers, 
                                 batch_first = True)
        # according to pytorch docs LSTM output is 
        # (batch_size,seq_len, num_directions * hidden_size)
        # when considering batch_first = True
        self.l_linear = torch.nn.Linear(self.n_hidden*self.seq_len, 1)
        
    
    def init_hidden(self, batch_size):
        # even with batch_first = True this remains same as docs
        hidden_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        cell_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        self.hidden = (hidden_state, cell_state)
    
    
    def forward(self, x):
        print(x)
        batch_size, seq_len = x.size()
        print(batch_size, seq_len, _)
        
        lstm_out, self.hidden = self.l_lstm(x,self.hidden)
        # lstm_out(with batch_first = True) is 
        # (batch_size,seq_len,num_directions * hidden_size)
        # for following linear layer we want to keep batch_size dimension and merge rest       
        # .contiguous() -> solves tensor compatibility error
        x = lstm_out.contiguous().view(batch_size,-1)
        return self.l_linear(x)

In [150]:
n_features = 2 # this is number of parallel inputs
n_timesteps = 3 # this is number of timesteps

# convert dataset into input/output
X, y = split_sequences(dataset, n_timesteps)
print(X.shape, y.shape)

# create NN
mv_net = MV_LSTM(n_features,n_timesteps)
criterion = torch.nn.MSELoss() # reduction='sum' created huge loss value
optimizer = torch.optim.Adam(mv_net.parameters(), lr=1e-1)

train_episodes = 500
batch_size = 16

(8, 3, 2) (8,)


In [151]:
mv_net.train()
for t in range(train_episodes):
    for b in range(0,len(X),batch_size):
        inpt = X[b:b+batch_size,:,:]
        target = y[b:b+batch_size]    
        
        x_batch = torch.tensor(inpt,dtype=torch.float32)    
        y_batch = torch.tensor(target,dtype=torch.float32)
    
        mv_net.init_hidden(x_batch.size(0))
    #    lstm_out, _ = mv_net.l_lstm(x_batch,nnet.hidden)    
    #    lstm_out.contiguous().view(x_batch.size(0),-1)
        output = mv_net(x_batch) 
        loss = criterion(output.view(-1), y_batch)  
        
        loss.backward()
        optimizer.step()        
        optimizer.zero_grad() 
    #print('step : ' , t , 'loss : ' , loss.item())

tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.]

tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.]

tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.]

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.]

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.]

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.]

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.

         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80., 85.]],

        [[70., 75.],
         [80., 85.],
         [90., 95.]]])
8 3 2
tensor([[[ 0.,  5.],
         [10., 15.],
         [20., 25.]],

        [[10., 15.],
         [20., 25.],
         [30., 35.]],

        [[20., 25.],
         [30., 35.],
         [40., 45.]],

        [[30., 35.],
         [40., 45.],
         [50., 55.]],

        [[40., 45.],
         [50., 55.],
         [60., 65.]],

        [[50., 55.],
         [60., 65.],
         [70., 75.]],

        [[60., 65.],
         [70., 75.],
         [80.